// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVl0-r54a81FiNG3diJu4MycKa0FmD2TU',
    appId: '1:520208817964:web:64abf55ccb57ac510dd689',
    messagingSenderId: '520208817964',
    projectId: 'mood-story-486ab',
    authDomain: 'mood-story-486ab.firebaseapp.com',
    storageBucket: 'mood-story-486ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcdGHFwSfFosNW5xTBQnI7z-9dhj464bM',
    appId: '1:520208817964:android:574e993a227d7b0c0dd689',
    messagingSenderId: '520208817964',
    projectId: 'mood-story-486ab',
    storageBucket: 'mood-story-486ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZHd-7T4ltGgLe6xzqvYgZg0WRoqXJi4A',
    appId: '1:520208817964:ios:8258aac9df4cfcda0dd689',
    messagingSenderId: '520208817964',
    projectId: 'mood-story-486ab',
    storageBucket: 'mood-story-486ab.appspot.com',
    iosBundleId: 'com.example.moodStory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZHd-7T4ltGgLe6xzqvYgZg0WRoqXJi4A',
    appId: '1:520208817964:ios:b699b463b94422100dd689',
    messagingSenderId: '520208817964',
    projectId: 'mood-story-486ab',
    storageBucket: 'mood-story-486ab.appspot.com',
    iosBundleId: 'com.example.moodStory.RunnerTests',
  );
}
